name: Run Sample App Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/test-workflow.yml
    with:
      test-path: ./Scripts/test_samples
