name: Run Sample App Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup iOS Simulator
        run: |
          xcode-select -p
          xcrun xcodebuild -version
          xcrun simctl list runtimes
          xcrun simctl list devicetypes
          xcrun simctl delete all
          CURRENT_SIMULATOR_UUID=$(xcrun simctl create TestDevice "iPhone 14")
          echo "CURRENT_SIMULATOR_UUID=$CURRENT_SIMULATOR_UUID" >> $GITHUB_ENV

      - name: Run Package Tests
        run: ./Scripts/test_package

